import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// viewport: 画面サイズとは別に、ブラウザ自体の見た目(テーマカラー)を
// 指定するためのNext.js専用のexport。
// themeColor: Safariはページの一番上の色をURLバーより上の余白(ステータス
// バー周り)にも反映する仕組みを持っている。ここを指定しないとデフォルトの
// 白になり、氷UIの背景(濃紺)から浮いて見えてしまっていた。
// body の背景グラデーションの開始色(globals.css参照)に合わせている。
// colorScheme: "dark" を伝えておくと、スクロールバーなど
// ブラウザ標準のUI部品もダークテーマ用の配色になる。
export const viewport: Viewport = {
    themeColor: "#05070f",
    colorScheme: "dark",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <Header />
                {children}
            </body>
        </html>
    );
}
